# Generated by Django 3.2.13 on 2022-10-17 05:18

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='img')),
            ],
        ),
    ]
